export type MistakeProfile = {
  mistake_id: string
  label: string
  description: string
  evidence_basis: string
}

export type TypeProfileV1 = {
  type_id: string
  canonical_name_ko: string
  subject: '공통수학1'
  unit_id: string
  subunit_id: string
  description: string
  core_concepts: string[]
  solution_strategies: string[]
  key_test_points: string[]
  common_mistakes: MistakeProfile[]
  prerequisite_types: string[]
  source_aliases: string[]
  representative_problem_ids: string[]
  confidence: number
  status: 'CANDIDATE' | 'VALIDATED' | 'REVIEW' | 'DEPRECATED'
  subtypes: Array<{ subtype_id: string; name: string; when: string }>
}

function m(typeId: string, slug: string, label: string, description: string, evidence_basis: string): MistakeProfile {
  return { mistake_id: `${typeId}.${slug}`, label, description, evidence_basis }
}

export const TYPE_PROFILES_V1: TypeProfileV1[] = [
  {
    type_id: 'POLY_ADD_SUB',
    canonical_name_ko: '다항식 덧셈·뺄셈과 정리',
    subject: '공통수학1',
    unit_id: '다항식',
    subunit_id: '다항식의 연산',
    description: '동류항을 모아 한 문자 기준 표준 형태로 정리한다.',
    core_concepts: ['동류항', '차수', '부호'],
    solution_strategies: ['기준 문자를 정한다', '동류항을 모은다', '오름/내림차순으로 배열한다'],
    key_test_points: ['다항식의 덧셈·뺄셈에서 동류항과 부호를 빠짐없이 정리할 수 있는가'],
    common_mistakes: [
      m('POLY_ADD_SUB', 'SIGN', '부호 처리 오류', '뺄셈을 괄호 분배하지 않고 항의 부호를 유지한다.', '덧셈·뺄셈 구조에서 괄호 앞 부호가 모든 항에 분배된다.'),
      m('POLY_ADD_SUB', 'UNLIKE', '이류항 결합', '차수나 문자가 다른 항을 동류항으로 합친다.', '동류항은 문자와 차수가 같아야 한다.'),
    ],
    prerequisite_types: [],
    source_aliases: ['다항식의 덧셈과 뺄셈', '01-1'],
    representative_problem_ids: [],
    confidence: 0.9,
    status: 'CANDIDATE',
    subtypes: [],
  },
  {
    type_id: 'POLY_MULTIPLY',
    canonical_name_ko: '다항식 곱셈',
    subject: '공통수학1',
    unit_id: '다항식',
    subunit_id: '다항식의 연산',
    description: '분배법칙과 곱셈 공식으로 전개한다.',
    core_concepts: ['분배법칙', '곱셈 공식'],
    solution_strategies: ['곱의 형태를 확인한다', '분배 또는 공식을 적용한다', '동류항을 정리한다'],
    key_test_points: ['곱셈 전개에서 특정 차수 계수를 빠짐없이 추출할 수 있는가'],
    common_mistakes: [
      m('POLY_MULTIPLY', '2AB', '제곱 전개 시 2ab 누락', '(a+b)^2에서 2ab를 빠뜨린다.', '곱셈 공식 전개는 중간항을 포함한다.'),
      m('POLY_MULTIPLY', 'MID', '중간항 누락', '다항×다항에서 일부 분배 항을 생략한다.', '모든 항의 쌍에 분배가 필요하다.'),
    ],
    prerequisite_types: ['POLY_ADD_SUB'],
    source_aliases: ['다항식의 곱셈', '01-2'],
    representative_problem_ids: [],
    confidence: 0.88,
    status: 'CANDIDATE',
    subtypes: [],
  },
  {
    type_id: 'POLY_PRODUCT_TRANSFORM',
    canonical_name_ko: '곱셈 공식의 변형',
    subject: '공통수학1',
    unit_id: '다항식',
    subunit_id: '다항식의 연산',
    description: '대칭량을 이용해 a^n±b^n 값을 구한다.',
    core_concepts: ['곱셈 공식', '대칭식'],
    solution_strategies: ['주어진 대칭량을 확인한다', '목표 차수 공식으로 변형한다', '값을 대입한다'],
    key_test_points: ['a+b, ab가 주어졌을 때 거듭제곱 합/차를 공식 변형으로 구할 수 있는가'],
    common_mistakes: [
      m('POLY_PRODUCT_TRANSFORM', 'DEGREE', '차수 혼동', 'a^2+b^2와 a^3+b^3 공식을 바꿔 쓴다.', '목표 식의 차수에 맞는 변형이 필요하다.'),
    ],
    prerequisite_types: ['POLY_MULTIPLY'],
    source_aliases: ['곱셈 공식의 변형', '01-3'],
    representative_problem_ids: [],
    confidence: 0.88,
    status: 'CANDIDATE',
    subtypes: [],
  },
  {
    type_id: 'POLY_DIVIDE',
    canonical_name_ko: '다항식 나눗셈',
    subject: '공통수학1',
    unit_id: '다항식',
    subunit_id: '다항식의 연산',
    description: '나눗셈 알고리즘과 A=BQ+R 관계를 사용한다.',
    core_concepts: ['몫', '나머지', '나머지 차수 조건'],
    solution_strategies: ['내림차순으로 정리한다', '나눗셈을 수행한다', 'A=BQ+R로 검산한다'],
    key_test_points: ['나머지 차수 조건을 지키며 몫과 나머지를 구할 수 있는가'],
    common_mistakes: [
      m('POLY_DIVIDE', 'DEG', '나머지 차수 조건 무시', '나머지의 차수가 나누는 다항식 이상이 되게 둔다.', '나머지 차수는 나누는 다항식보다 낮아야 한다.'),
    ],
    prerequisite_types: ['POLY_ADD_SUB'],
    source_aliases: ['다항식의 나눗셈', '01-4'],
    representative_problem_ids: [],
    confidence: 0.86,
    status: 'CANDIDATE',
    subtypes: [],
  },
  {
    type_id: 'IDENTITY_PROPERTY',
    canonical_name_ko: '항등식의 성질',
    subject: '공통수학1',
    unit_id: '다항식',
    subunit_id: '나머지 정리와 인수분해',
    description: '문자에 어떤 값을 넣어도 성립하는 등식을 다룬다.',
    core_concepts: ['항등식', '방정식과의 구분'],
    solution_strategies: ['항등 여부를 확인한다', '대입 또는 계수 비교를 선택한다', '조건을 적용한다'],
    key_test_points: ['항등식과 방정식을 구분하고 항등 조건을 사용할 수 있는가'],
    common_mistakes: [
      m('IDENTITY_PROPERTY', 'EQ', '방정식으로 오인', '특정 해만 존재하는 방정식으로 취급한다.', '항등식은 모든 값에서 성립한다.'),
    ],
    prerequisite_types: ['POLY_ADD_SUB'],
    source_aliases: ['항등식', '02-1'],
    representative_problem_ids: [],
    confidence: 0.86,
    status: 'CANDIDATE',
    subtypes: [],
  },
  {
    type_id: 'UNDETERMINED_COEFF',
    canonical_name_ko: '미정계수 결정',
    subject: '공통수학1',
    unit_id: '다항식',
    subunit_id: '나머지 정리와 인수분해',
    description: '항등식의 계수 비교 또는 특정값 대입으로 미정계수를 구한다.',
    core_concepts: ['항등식', '계수 비교', '수치 대입'],
    solution_strategies: ['양변을 같은 기준으로 전개한다', '계수 비교 또는 특정값 대입을 선택한다', '연립으로 미지수를 푼다'],
    key_test_points: ['계수 비교와 대입 중 조건에 맞는 전략으로 미정계수를 결정할 수 있는가'],
    common_mistakes: [
      m('UNDETERMINED_COEFF', 'TERM', '차수 누락', '한쪽 전개에서 특정 차수 항을 비교하지 않는다.', '모든 대응 차수의 계수를 맞춰야 한다.'),
      m('UNDETERMINED_COEFF', 'SUB', '대입값 선택 오류', '계수가 소거되지 않는 값을 대입해 계산이 꼬인다.', '수치 대입형은 미지 계수가 분리되는 값을 고른다.'),
    ],
    prerequisite_types: ['IDENTITY_PROPERTY'],
    source_aliases: ['미정계수', '계수 비교형', '02-2'],
    representative_problem_ids: [],
    confidence: 0.88,
    status: 'CANDIDATE',
    subtypes: [
      { subtype_id: 'UNDETERMINED_COEFF_COMPARE', name: '계수 비교형', when: '양변을 전개해 같은 차수 계수를 대응한다' },
      { subtype_id: 'UNDETERMINED_SUBSTITUTION', name: '수치 대입형', when: '특정 값을 대입해 미정계수를 분리한다' },
    ],
  },
  {
    type_id: 'REMAINDER_FACTOR_THEOREM',
    canonical_name_ko: '나머지정리·인수정리',
    subject: '공통수학1',
    unit_id: '다항식',
    subunit_id: '나머지 정리와 인수분해',
    description: 'P(x)를 x-a로 나눈 나머지는 P(a)이고, P(a)=0이면 x-a가 인수이다.',
    core_concepts: ['나머지정리', '인수정리'],
    solution_strategies: ['나누는 일차식을 확인한다', 'P(a)를 계산한다', '나머지 또는 인수 여부를 판정한다'],
    key_test_points: ['ax+b로 나눌 때 보정까지 포함해 나머지/인수를 판정할 수 있는가'],
    common_mistakes: [
      m('REMAINDER_FACTOR_THEOREM', 'SIGN', '대입값 부호 오류', 'x+a로 나눌 때 P(-a)가 아니라 P(a)를 대입한다.', 'x-a 꼴로 맞춘 뒤 a를 대입해야 한다.'),
    ],
    prerequisite_types: ['POLY_DIVIDE'],
    source_aliases: ['나머지 정리', '인수 정리', '02-3'],
    representative_problem_ids: [],
    confidence: 0.9,
    status: 'CANDIDATE',
    subtypes: [],
  },
  {
    type_id: 'SYNTHETIC_DIVISION',
    canonical_name_ko: '조립제법',
    subject: '공통수학1',
    unit_id: '다항식',
    subunit_id: '나머지 정리와 인수분해',
    description: '일차식 나눗셈을 계수만으로 수행한다.',
    core_concepts: ['조립제법', '결손항'],
    solution_strategies: ['계수를 배열한다', '결손항 0을 채운다', '몫과 나머지를 읽는다'],
    key_test_points: ['결손항을 포함하여 조립제법으로 몫과 나머지를 구할 수 있는가'],
    common_mistakes: [
      m('SYNTHETIC_DIVISION', 'ZERO', '결손항 0 누락', '중간 차수가 없을 때 0을 넣지 않는다.', '계수 배열은 모든 차수를 채워야 한다.'),
    ],
    prerequisite_types: ['REMAINDER_FACTOR_THEOREM'],
    source_aliases: ['조립제법', '02-4'],
    representative_problem_ids: [],
    confidence: 0.86,
    status: 'CANDIDATE',
    subtypes: [],
  },
  {
    type_id: 'POLY_FACTORING',
    canonical_name_ko: '다항식 인수분해',
    subject: '공통수학1',
    unit_id: '다항식',
    subunit_id: '나머지 정리와 인수분해',
    description: '공식과 공통인수로 다항식을 인수 곱으로 나타낸다.',
    core_concepts: ['공통인수', '인수분해 공식'],
    solution_strategies: ['공통인수를 뺀다', '공식을 식별한다', '완전히 분해될 때까지 반복한다'],
    key_test_points: ['적절한 공식을 선택해 다항식을 완전히 인수분해할 수 있는가'],
    common_mistakes: [
      m('POLY_FACTORING', 'COMMON', '공통인수 누락', '공식부터 적용하고 공통인수를 남긴다.', '공통인수 추출이 선행된다.'),
    ],
    prerequisite_types: ['POLY_MULTIPLY'],
    source_aliases: ['복잡한 식의 인수분해', '02-5'],
    representative_problem_ids: [],
    confidence: 0.86,
    status: 'CANDIDATE',
    subtypes: [],
  },
  {
    type_id: 'COMPLEX_EQUALITY',
    canonical_name_ko: '복소수가 같을 조건',
    subject: '공통수학1',
    unit_id: '방정식',
    subunit_id: '복소수',
    description: '실수부·허수부가 각각 같으면 두 복소수가 같다.',
    core_concepts: ['실수부', '허수부'],
    solution_strategies: ['실수부와 허수부를 분리한다', '두 등식을 세운다', '연립하여 푼다'],
    key_test_points: ['복소수 등식을 실수부/허수부 비교로 풀 수 있는가'],
    common_mistakes: [
      m('COMPLEX_EQUALITY', 'PART', '실수부·허수부 혼동', 'i의 계수를 실수부와 섞는다.', '같음 조건은 두 부분을 독립 비교한다.'),
    ],
    prerequisite_types: [],
    source_aliases: ['복소수가 서로 같을 조건', '03-2'],
    representative_problem_ids: [],
    confidence: 0.84,
    status: 'CANDIDATE',
    subtypes: [],
  },
  {
    type_id: 'COMPLEX_CONJUGATE',
    canonical_name_ko: '켤레복소수',
    subject: '공통수학1',
    unit_id: '방정식',
    subunit_id: '복소수',
    description: '켤레복소수의 합·곱이 실수가 되는 성질을 사용한다.',
    core_concepts: ['켤레복소수', '실수 조건'],
    solution_strategies: ['켤레를 표시한다', '합/곱 성질을 적용한다', '실수 조건을 확인한다'],
    key_test_points: ['켤레복소수 성질로 식의 값이 실수인지 판정할 수 있는가'],
    common_mistakes: [
      m('COMPLEX_CONJUGATE', 'IM', '허수부 부호 누락', '켤레에서 허수부 부호를 바꾸지 않는다.', '켤레는 허수부 부호만 반전한다.'),
    ],
    prerequisite_types: ['COMPLEX_ARITHMETIC'],
    source_aliases: ['켤레복소수', '03-3'],
    representative_problem_ids: [],
    confidence: 0.84,
    status: 'CANDIDATE',
    subtypes: [],
  },
  {
    type_id: 'COMPLEX_ARITHMETIC',
    canonical_name_ko: '복소수 사칙연산',
    subject: '공통수학1',
    unit_id: '방정식',
    subunit_id: '복소수',
    description: 'i^2=-1을 이용해 복소수를 계산하고 표준형으로 나타낸다.',
    core_concepts: ['허수단위', 'i의 거듭제곱'],
    solution_strategies: ['i의 거듭제곱을 정리한다', '연산을 수행한다', 'a+bi 꼴로 나타낸다'],
    key_test_points: ['i의 순환과 분모 실수화까지 포함해 복소수 연산을 할 수 있는가'],
    common_mistakes: [
      m('COMPLEX_ARITHMETIC', 'POW', 'i 지수 순환 오류', 'i^n의 나머지를 잘못 읽는다.', 'i^n은 4를 주기로 순환한다.'),
    ],
    prerequisite_types: [],
    source_aliases: ['복소수의 사칙연산', '음수의 제곱근', '03-1', '03-5'],
    representative_problem_ids: [],
    confidence: 0.86,
    status: 'CANDIDATE',
    subtypes: [],
  },
  {
    type_id: 'QUADRATIC_SOLVE',
    canonical_name_ko: '이차방정식 풀이',
    subject: '공통수학1',
    unit_id: '방정식',
    subunit_id: '이차방정식',
    description: '인수분해, 제곱근, 근의 공식으로 해를 구한다.',
    core_concepts: ['이차방정식', '근의 공식'],
    solution_strategies: ['표준형으로 정리한다', '인수분해 또는 근의 공식을 선택한다', '해를 구한다'],
    key_test_points: ['풀이 방법을 선택해 이차방정식의 해를 모두 구할 수 있는가'],
    common_mistakes: [
      m('QUADRATIC_SOLVE', 'DOUBLE', '중근을 한 근만 셈', '중근을 하나의 해로만 적고 끝낸다.', '중근도 해의 개수 조건에 반영된다.'),
    ],
    prerequisite_types: [],
    source_aliases: ['이차방정식의 풀이', '04-1'],
    representative_problem_ids: [],
    confidence: 0.86,
    status: 'CANDIDATE',
    subtypes: [],
  },
  {
    type_id: 'QUADRATIC_DISCRIMINANT',
    canonical_name_ko: '근의 판별',
    subject: '공통수학1',
    unit_id: '방정식',
    subunit_id: '이차방정식',
    description: '판별식 D로 실근의 개수와 종류를 판정한다.',
    core_concepts: ['판별식'],
    solution_strategies: ['표준형 계수를 읽는다', 'D를 계산한다', '근의 개수/종류를 판정한다'],
    key_test_points: ['판별식의 부호로 실근·허근·중근을 구별할 수 있는가'],
    common_mistakes: [
      m('QUADRATIC_DISCRIMINANT', 'D', 'D 식 오류', 'b^2-4ac에서 부호나 계수를 잘못 넣는다.', '표준형 ax^2+bx+c의 계수로 D를 계산한다.'),
    ],
    prerequisite_types: ['QUADRATIC_SOLVE'],
    source_aliases: ['근의 판별', '04-2'],
    representative_problem_ids: [],
    confidence: 0.88,
    status: 'CANDIDATE',
    subtypes: [],
  },
  {
    type_id: 'QUADRATIC_VIETAS',
    canonical_name_ko: '근과 계수의 관계',
    subject: '공통수학1',
    unit_id: '방정식',
    subunit_id: '이차방정식',
    description: '두 근의 합과 곱을 계수로 나타내 대칭식을 계산한다.',
    core_concepts: ['근의 합', '근의 곱', '대칭식'],
    solution_strategies: ['합과 곱을 읽는다', '목표 대칭식을 변형한다', '값을 계산한다'],
    key_test_points: ['합·곱의 부호를 계수와 맞게 읽어 대칭식 값을 구할 수 있는가'],
    common_mistakes: [
      m('QUADRATIC_VIETAS', 'SIGN', '근과 계수 관계의 부호 반전', '합을 -b/a가 아니라 b/a로 둔다.', 'ax^2+bx+c=0에서 합은 -b/a, 곱은 c/a이다.'),
    ],
    prerequisite_types: ['QUADRATIC_SOLVE'],
    source_aliases: ['근과 계수의 관계', '이차방정식의 켤레근', '04-3', '04-5'],
    representative_problem_ids: [],
    confidence: 0.9,
    status: 'CANDIDATE',
    subtypes: [],
  },
  {
    type_id: 'QUADRATIC_FACTOR',
    canonical_name_ko: '이차식 인수분해',
    subject: '공통수학1',
    unit_id: '방정식',
    subunit_id: '이차방정식',
    description: '이차식을 일차식의 곱으로 인수분해한다.',
    core_concepts: ['이차식 인수', '근'],
    solution_strategies: ['근 또는 계수 조건을 확인한다', '일차 인수를 구성한다', '검산한다'],
    key_test_points: ['근 조건으로 이차식을 실계수 범위에서 인수분해할 수 있는가'],
    common_mistakes: [
      m('QUADRATIC_FACTOR', 'LEAD', '인수 상수배 누락', '최고차 계수 a를 인수에 넣지 않는다.', 'a(x-r)(x-s) 형태가 필요하다.'),
    ],
    prerequisite_types: ['QUADRATIC_SOLVE'],
    source_aliases: ['이차식의 인수분해', '04-4'],
    representative_problem_ids: [],
    confidence: 0.84,
    status: 'CANDIDATE',
    subtypes: [],
  },
  {
    type_id: 'QUAD_FN_RELATION',
    canonical_name_ko: '이차함수와 이차방정식의 관계',
    subject: '공통수학1',
    unit_id: '방정식',
    subunit_id: '이차방정식과 이차함수',
    description: '그래프와 x축 또는 직선의 교점으로 근을 해석한다.',
    core_concepts: ['교점', '실근', '위치 관계'],
    solution_strategies: ['함수식을 확인한다', '교점 조건을 세운다', '근/교점을 대응한다'],
    key_test_points: ['그래프 교점 개수와 이차방정식 실근을 연결할 수 있는가'],
    common_mistakes: [
      m('QUAD_FN_RELATION', 'AXIS', '교점과 근 혼동', 'y절편을 근으로 읽는다.', '방정식 f(x)=0의 근은 x축 교점이다.'),
    ],
    prerequisite_types: ['QUADRATIC_SOLVE'],
    source_aliases: ['이차방정식과 이차함수', '이차함수의 그래프와 직선의 위치 관계', '05-1', '05-2'],
    representative_problem_ids: [],
    confidence: 0.82,
    status: 'CANDIDATE',
    subtypes: [],
  },
  {
    type_id: 'SIMULTANEOUS_QUAD',
    canonical_name_ko: '연립이차방정식',
    subject: '공통수학1',
    unit_id: '방정식',
    subunit_id: '여러 가지 방정식',
    description: '두 방정식을 연립하여 해 쌍을 구한다.',
    core_concepts: ['대입', '가감', '해 쌍'],
    solution_strategies: ['한 문자를 소거한다', '이차방정식을 푼다', '나머지 문자를 구한다'],
    key_test_points: ['대입·가감으로 연립이차의 해 쌍을 빠짐없이 구할 수 있는가'],
    common_mistakes: [
      m('SIMULTANEOUS_QUAD', 'PAIR', '해 쌍 누락', '한 문자 해만 구하고 짝을 만들지 않는다.', '각 근에 대응하는 다른 문자 값이 해의 일부이다.'),
    ],
    prerequisite_types: ['QUADRATIC_SOLVE'],
    source_aliases: ['연립이차방정식', '06-2'],
    representative_problem_ids: [],
    confidence: 0.8,
    status: 'CANDIDATE',
    subtypes: [],
  },
  {
    type_id: 'CUBIC_QUARTIC_EQ',
    canonical_name_ko: '삼차·사차방정식',
    subject: '공통수학1',
    unit_id: '방정식',
    subunit_id: '여러 가지 방정식',
    description: '인수정리로 차수를 낮춘 뒤 이차방정식을 푼다.',
    core_concepts: ['인수정리', '고차방정식'],
    solution_strategies: ['가능한 유리근을 시험한다', '인수분해로 차수를 낮춘다', '이차 인수를 푼다'],
    key_test_points: ['삼차·사차식을 인수분해해 모든 근을 구할 수 있는가'],
    common_mistakes: [
      m('CUBIC_QUARTIC_EQ', 'ROOT', '유리근 후보 누락', '상수항의 약수 후보를 일부만 시험한다.', '가능한 유리근은 상수항 약수/최고차 약수이다.'),
    ],
    prerequisite_types: ['REMAINDER_FACTOR_THEOREM', 'QUADRATIC_SOLVE'],
    source_aliases: ['삼차방정식과 사차방정식', '06-1'],
    representative_problem_ids: [],
    confidence: 0.72,
    status: 'CANDIDATE',
    subtypes: [],
  },
  {
    type_id: 'LINEAR_INEQUALITY',
    canonical_name_ko: '일차부등식 풀이',
    subject: '공통수학1',
    unit_id: '부등식',
    subunit_id: '일차부등식',
    description: '부등식의 성질로 일차·연립일차부등식의 해집합을 구한다.',
    core_concepts: ['부등식 방향', '교집합'],
    solution_strategies: ['항을 정리한다', '계수 부호에 따라 방향을 정한다', '해집합을 나타낸다'],
    key_test_points: ['음수를 곱할 때 방향 반전과 연립 교집합을 지킬 수 있는가'],
    common_mistakes: [
      m('LINEAR_INEQUALITY', 'FLIP', '부등식 방향 미반전', '음수를 곱하거나 나눌 때 방향을 그대로 둔다.', '음수 배에서는 부등식 방향이 바뀐다.'),
    ],
    prerequisite_types: [],
    source_aliases: ['일차부등식', '부등식 ax>b의 풀이', 'A < B < C 꼴의 부등식', '07-1'],
    representative_problem_ids: [],
    confidence: 0.86,
    status: 'CANDIDATE',
    subtypes: [],
  },
  {
    type_id: 'QUADRATIC_INEQUALITY',
    canonical_name_ko: '이차부등식 풀이',
    subject: '공통수학1',
    unit_id: '부등식',
    subunit_id: '이차부등식',
    description: '이차함수 그래프 또는 인수 부호로 해집합을 구한다.',
    core_concepts: ['근', '구간 부호', '등호'],
    solution_strategies: ['근을 구한다', '구간 부호를 본다', '부등식 방향에 맞는 구간을 택한다'],
    key_test_points: ['이차식의 부호와 등호 포함 여부를 해집합에 반영할 수 있는가'],
    common_mistakes: [
      m('QUADRATIC_INEQUALITY', 'EQ', '등호 포함 여부 누락', '≤를 <로 바꿔 근을 해에서 뺀다.', '등호가 있으면 근도 해에 포함한다.'),
    ],
    prerequisite_types: ['QUADRATIC_SOLVE', 'LINEAR_INEQUALITY'],
    source_aliases: ['이차부등식', '08-1'],
    representative_problem_ids: [],
    confidence: 0.84,
    status: 'CANDIDATE',
    subtypes: [],
  },
  {
    type_id: 'COUNTING_PERM_COMB',
    canonical_name_ko: '순열·조합 계산',
    subject: '공통수학1',
    unit_id: '순열과 조합',
    subunit_id: '순열과 조합',
    description: '순서 유무에 따라 순열 또는 조합으로 경우의 수를 센다.',
    core_concepts: ['곱의 법칙', '순열', '조합'],
    solution_strategies: ['순서 유무를 판단한다', '공식을 선택한다', '제한 조건을 반영한다'],
    key_test_points: ['순열과 조합을 구별하고 제한 조건을 빠짐없이 셀 수 있는가'],
    common_mistakes: [
      m('COUNTING_PERM_COMB', 'PC', '순열과 조합 선택 기준 혼동', '순서가 있는데 조합으로 센다.', '순서가 있으면 순열, 없으면 조합이다.'),
    ],
    prerequisite_types: [],
    source_aliases: ['순열', '조합', '경우의 수', '09-1'],
    representative_problem_ids: [],
    confidence: 0.86,
    status: 'CANDIDATE',
    subtypes: [
      { subtype_id: 'COUNTING_PERM', name: '순열형', when: '순서가 있는 배열' },
      { subtype_id: 'COUNTING_COMB', name: '조합형', when: '순서가 없는 선택' },
    ],
  },
  {
    type_id: 'MATRIX_ARITHMETIC',
    canonical_name_ko: '행렬의 연산',
    subject: '공통수학1',
    unit_id: '행렬',
    subunit_id: '행렬과 그 연산',
    description: '행렬의 덧셈·실수배·곱셈 규칙을 적용한다.',
    core_concepts: ['행렬의 꼴', '행렬 곱'],
    solution_strategies: ['꼴을 확인한다', '정의에 따라 연산한다', '교환법칙 예외를 점검한다'],
    key_test_points: ['행렬 곱셈과 성분별 연산, 교환법칙 성립 여부를 구별할 수 있는가'],
    common_mistakes: [
      m('MATRIX_ARITHMETIC', 'HADAMARD', '행렬 곱셈과 성분별 곱셈 혼동', 'AB를 같은 위치 성분끼리 곱한 것으로 계산한다.', '행렬 곱은 행×열 내적이다.'),
      m('MATRIX_ARITHMETIC', 'COMM', '곱셈 교환법칙 오용', 'AB=BA라고 단정한다.', '행렬 곱은 일반적으로 교환되지 않는다.'),
    ],
    prerequisite_types: [],
    source_aliases: ['행렬과 그 연산', '10-1'],
    representative_problem_ids: [],
    confidence: 0.88,
    status: 'CANDIDATE',
    subtypes: [],
  },
]

export function profileById(typeId: string): TypeProfileV1 | undefined {
  return TYPE_PROFILES_V1.find((row) => row.type_id === typeId)
}
